import { v4 as uuidv4 } from "uuid";

const mockInvoices = {
  Guest_5939: {
    id: "Guest_5939",
    createdAt: "2024-12-01",
    paymentDue: "2024-12-15",
    description: "Website redesign project",
    paymentTerms: 14,
    clientName: "Jane Smith",
    clientEmail: "jane.smith@example.com",
    status: "pending",
    senderAddress: {
      street: "789 Maple Street",
      city: "Edinburgh",
      postCode: "EH1 1TH",
      country: "Scotland",
    },
    clientAddress: {
      street: "123 Oak Street",
      city: "Glasgow",
      postCode: "G1 2AB",
      country: "Scotland",
    },
    items: [
      { name: "Web Design", quantity: 1, price: 100, total: 100 },
      { name: "Hosting Fee", quantity: 1, price: 20, total: 20 },
    ],
    total: 120,
  },
  Guest_64e9: {
    id: "Guest_64e9",
    createdAt: "2024-11-15",
    paymentDue: "2024-11-30",
    description: "SEO Optimization services",
    paymentTerms: 7,
    clientName: "John Doe",
    clientEmail: "john.doe@example.com",
    status: "paid",
    senderAddress: {
      street: "45 King Street",
      city: "London",
      postCode: "EC1A 1BB",
      country: "England",
    },
    clientAddress: {
      street: "78 Queen Street",
      city: "Brighton",
      postCode: "BN1 1AA",
      country: "England",
    },
    items: [{ name: "SEO Optimization", quantity: 2, price: 100, total: 200 }],
    total: 200,
  },
  Guest_74e7: {
    id: "Guest_74e7",
    createdAt: "2024-12-20",
    paymentDue: "2025-01-05",
    description: "Content writing for marketing",
    paymentTerms: 14,
    clientName: "Emma Johnson",
    clientEmail: "emma.johnson@example.com",
    status: "draft",
    senderAddress: {
      street: "101 High Street",
      city: "Cardiff",
      postCode: "CF10 1AA",
      country: "Wales",
    },
    clientAddress: {
      street: "11 Rose Avenue",
      city: "Swansea",
      postCode: "SA1 1AA",
      country: "Wales",
    },
    items: [{ name: "Content Writing", quantity: 5, price: 90, total: 450 }],
    total: 450,
  },
  Guest_9587: {
    id: "Guest_9587",
    createdAt: "2024-12-22",
    paymentDue: "2025-01-10",
    description: "Logo Design and Branding",
    paymentTerms: 30,
    clientName: "Liam Miller",
    clientEmail: "liam.miller@example.com",
    status: "pending",
    senderAddress: {
      street: "500 Main Street",
      city: "Manchester",
      postCode: "M1 2JQ",
      country: "England",
    },
    clientAddress: {
      street: "15 Elm Road",
      city: "Bristol",
      postCode: "BS1 5XY",
      country: "England",
    },
    items: [
      { name: "Logo Design", quantity: 1, price: 200, total: 200 },
      { name: "Branding Package", quantity: 1, price: 150, total: 150 },
    ],
    total: 350,
  },
  Guest_2158: {
    id: "Guest_2158",
    createdAt: "2024-12-18",
    paymentDue: "2024-12-25",
    description: "App Development",
    paymentTerms: 7,
    clientName: "Sophia White",
    clientEmail: "sophia.white@example.com",
    status: "paid",
    senderAddress: {
      street: "32 River View",
      city: "Newcastle",
      postCode: "NE1 6SA",
      country: "England",
    },
    clientAddress: {
      street: "100 Beach Road",
      city: "London",
      postCode: "E1 7DG",
      country: "England",
    },
    items: [{ name: "App Development", quantity: 1, price: 500, total: 500 }],
    total: 500,
  },
  Guest_3673: {
    id: "Guest_3673",
    createdAt: "2024-12-23",
    paymentDue: "2025-01-09",
    description: "Social Media Marketing",
    paymentTerms: 14,
    clientName: "Ava Brown",
    clientEmail: "ava.brown@example.com",
    status: "pending",
    senderAddress: {
      street: "101 Queen Street",
      city: "Liverpool",
      postCode: "L3 5AX",
      country: "England",
    },
    clientAddress: {
      street: "22 Cherry Lane",
      city: "Manchester",
      postCode: "M2 3JD",
      country: "England",
    },
    items: [
      { name: "Social Media Campaign", quantity: 3, price: 50, total: 150 },
      { name: "Consulting", quantity: 1, price: 100, total: 100 },
    ],
    total: 250,
  },
  Guest_4862: {
    id: "Guest_4862",
    createdAt: "2024-12-16",
    paymentDue: "2024-12-30",
    description: "Website Development for Ecommerce",
    paymentTerms: 30,
    clientName: "Oliver Green",
    clientEmail: "oliver.green@example.com",
    status: "pending",
    senderAddress: {
      street: "123 Riverbank",
      city: "Dublin",
      postCode: "D02 3GG",
      country: "Ireland",
    },
    clientAddress: {
      street: "50 Park Lane",
      city: "Cork",
      postCode: "T12 V2X3",
      country: "Ireland",
    },
    items: [
      { name: "Ecommerce Website", quantity: 1, price: 400, total: 400 },
      { name: "Domain Registration", quantity: 1, price: 30, total: 30 },
    ],
    total: 430,
  },
};

export default mockInvoices;
